[project]
name = "mdc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.1",
    "polars>=1.32.3",
    "tqdm>=4.67.1",
]
