# Small Sample Configuration for Testing
# BERT Training Data Generator Configuration

# Data paths
data:
  pmc_dir: "data/pmc"
  corpus_file: "data/corpus/corpus_consolidated.json"
  pmc_ids_file: "data/pmc/PMC-ids.csv"

# Model configuration
model:
  tokenizer_name: "answerdotai/ModernBERT-base"

# Generation settings
generation:
  num_samples: 50        # Small sample for testing
  positive_ratio: 0.8    # Higher ratio for more positive examples
  min_token_length: 5    # Shorter minimum for testing
  max_token_length: 64   # Shorter maximum for faster processing
  text_unit: "sentence"
  random_seed: 42

# Output settings
output:
  output_path: "training_data/small_sample.jsonl"
  output_format: "jsonl"

# Processing settings
processing:
  include_restoration_test: true
  sampling_percentage: 0.01  # Use only 1% of files for speed

# Text processing strategies
text_processing:
  cropper:
    strategy: "sentence"
    sentence_context: 1
  
  negative_sampler:
    strategy: "random"
    sample_length: 50
    min_gap: 20

# Logging
logging:
  verbose: true
  progress_bar: true